version: 2

sources:

 - name: CLASS_TES2
   description: "Class test data"
   database: CLASS_TEST
   schema: CLASS_TEST
   tables:
     - name: CUSTOMER
       description: "this is the customer table info"
     - name: ORDERS
       description: "this is orders table info"
     - name: PRODUCT
       description: "THis is a product table info"